const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      countInStack: 10,
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 120,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
      countInStack: 17,
    },
    {
      _id: '3',
      name: 'Lacoste Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 120,
      brand: 'Locoste',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
      countInStack: 0,
    },
    {
      _id: '4',
      name: 'Puma Shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 130,
      brand: 'Puma',
      rating: 1.5,
      numReviews: 10,
      description: 'high quality product',
      countInStack: 5,
    },
    {
      _id: '5',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 150,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
      countInStack: 7,
    },
    {
      _id: '6',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 110,
      brand: 'Nike',
      rating: 2,
      numReviews: 10,
      description: 'high quality product',
      countInStack: 0,
    },
  ],
};

export default data;
