const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 120,
            brand: 'Locoste',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Puma Shirt',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 120,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p6.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }
    ]
}